scripts/logcrawler.py
PYTHON_F401: 'Module imported but unused.'.  This is a pep8 error code.          See <a href='https://pep8.readthedocs.io/en/latest/intro.html#error-codes'>        here for a complete list of error codes</a>.        
It was fixed with <a href='https://github.com/myint/autoflake'>autoflake</a>.        
This fix is probably safe because the module was not called anywhere.  But if the removed module had global side-effects,        these will be missing and could cause issues.
=> Fixed 1 issue of type: PYTHON_F401 throughout 1 file in repo.

.travis.yml
- Attempts to fix the recent Travis errors on the macOS builds by using a newer brew formula to install Python.
The aw-webui upgrade includes:
- Fixes an annoying bug in aw-webui (#313)
- Fixes the favicon for aw-webui
- Adds the filter-by-category feature to the activity view
=> updated aw-server, attempted travis fix

.appveyor.yml, .gitmodules, .travis.yml, Makefile
=> Replace aw-server-python with aw-server-rust

aw.spec
Solves the macOS side of #353
Tested this locally and it did work, ready to merge if CI passes. 
Should probably bump version number to something like 0.9 as well.
Also as a note for the future: I locally tried a build without python aw-server at all, and besides aw-qt having the hard coded UI button for "aw-server" it worked fine.
=> Add aw-server-rust binary to pyinstaller bundles 

.travis.yml
These are the least refactory and most working changes from the travis things I tried today.
Renaming the "matrix", local_dir and removing skip_cleanup is just moving to more recent travis standards, and they don't change the build at all.
These caches should make the build somewhat faster with no real downside. Pip, .rustup and brew caches are fairly safe, and cargo's target should also be faster than recompiling dependencies etc. every time, but it will still rebuild the relevant artifacts if source files have changes.
=> Add some dependency caching, fix a couple of travis warnings

aw.spec
Correct submodule versions and updated CFBundleShortVersionString
For future reference: it seems like LGTM analysis fails (instead of skips) with some not found error if there's a broken submodule link or something of the sort in a PR, will keep an eye on that.
=> Added back rm node_modules/.cache fix, updated aw-server-rust with test_full fix 

.appveyor.yml, .travis.yml, Makefile, poetry.lock, pyproject.toml, scripts/dev-requirements.txt
`make build` now uses `poetry install` to install all Python packages and dependencies. This makes CI actually use the `poetry.lock` files to resolve dependencies (which `pip install .` doesn't). 
It also:
- Changes the Windows/Appveyor builds to use 64bit Python
- Changes all uses of `python3` to `python` (since `python3` isn't available on Windows)
- Adds virtualenvs to Windows and macOS builds
Fixes #378
=> build: switched to using poetry for `make build`

README.md
Uppercased and added expansion to AFK acronym to use in "About" section of README.md
=> Add explanation of AFK acronym to README

aw.spec
Fixes #441
I have no idea if I'm doing this right.
Does it look correct to you @xylix? I guess we'll have to test it anyway but would be nice to understand how things really work here. 
I ran `7z x activitywatch-v0.9.2-macos-x86_64.dmg` to inspect the last released `dmg` and get an understanding of how things are structured, but found more questions than answers.
Questions:
- What is the working directory for aw-server-rust when run on macOS?
- Will aw-server-rust find the files in `ActivityWatch.app/Contents/Resources/aw-server-rust/static` without changes? (@johan-bjareholt)
=> fix: fixed inclusion of aw-webui for use with aw-server-rust (fixes #441)

.github/workflows/build.yml, .travis.yml, poetry.lock, pyproject.toml
Working on support for Python 3.8 and 3.9, since PyInstaller now supports it.
Also, finally updates to a recent PyQt5 (which may fix some issues).
Requires: https://github.com/ActivityWatch/aw-qt/pull/67
=> ci: updated PyInstaller and dev locks, added Python 3.8 and 3.9 as experimental

scripts/package/activitywatch-setup.iss
Closes #637.
I found information about this [here](https://jrsoftware.org/ishelp/index.php?topic=setup_uninstalldisplayname), but I didn't build it myself, since this process took me a lot of time and never finished.
=> build(windows): specify name of app in list of installed apps

Makefile, aw.spec, scripts/notarize.sh
1. Entitlements file belongs into the `Exe()` not `Bundle()`, ideally each executable gets its own entitlements file (some processes may need more or less permissions than others).
2. `NSAppleEventsUsageDescription` to allow sending Apple Events (Hardened runtime will complain)
3. Notarization script (needs testing!)
TODO:
* Get rid of `scripts/codesign.sh` <- will not be required, better to codesign through `PyInstaller`
If ActivityWatch ships shared libraries that get dynamically loaded then those will also have to be code signed.
cc @ErikBjare please make sure that you've registered `net.activitywatch.ActivityWatch`  as application identifier through the Apple Developer Program (through the website). It's not required for notarization as far as I know, but once you start creating …
=> fix(dist): move entitlements , `NSAppleEventsUsageDescription`

Makefile
May have been what fixed build issue on M1 mac/with poetry
https://github.com/ActivityWatch/activitywatch/issues/433#issuecomment-998992792
@ErikBjare as suggested!
=> ci: change use `python` to `python3`

Makefile
This would probably be better done as a preprocessor step or something
=> ci: skip building aw-server-rust if cargo is not installed

.tool-versions
This explicitly defines the runtime dependencies
required to compile and develop the application.
If it doesn't feel right to have this in the repo, I can submit
a gitignore change to exclude this file. It's very helpful to have
these versions defined explicitly rather than reading through documentation
to determine what versions are required. Additionally, it looks like asdf
is picking up more community adoption as time goes on.
=> Adding asfd tool-versions file

aw.spec
Needed for PR CI runs to get green, etc.
=> ci: enable macOS builds to complete when secrets not set

.github/workflows/winget.yml
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @ActivityWatchBot.
> **Note** The Personal Access Token should come from the @ActivityWatchBot account.
* Resolves https://github.com/ActivityWatch/activitywatch/issues/752
=> ci(distribution): auto-release to winget

.github/workflows/build.yml
https://github.com/ActivityWatch/aw-server-rust/issues/180
=> ci: enable cargo caching on macOS again (hoping issue has been fixed upstream)

.github/workflows/winget.yml
@ErikBjare please give token `workflow` permission also. You can re-run the job after that.
Reference: https://github.com/ActivityWatch/activitywatch/actions/runs/3130622310/jobs/5081066783
=> ci(distribution): use versioned tag for winget-releaser

.github/workflows/build.yml
Closes: https://github.com/ActivityWatch/activitywatch/issues/725
=> ci: build AppImage releases

.github/workflows/build.yml
Gets rid of some CI warnings.
See https://github.com/actions-rs/toolchain/issues/216 for the fate of actions-rs.
=> ci: switch from actions-rs/toolchain to maintained dtolnay/rust-toolchain

.github/workflows/build.yml, .github/workflows/test.yml, .tool-versions
Due to issue https://github.com/ActivityWatch/activitywatch/issues/936 caused by #931
=> ci: downgrade to Python 3.9

aw.spec
Continuing on https://github.com/ActivityWatch/activitywatch/pull/934
The `.app` didn't contain `aw-watcher-input` or `aw-notify`.
This fixes that.
=> fix: trying to fix building extras on macOS
