ActivityWatch/activitywatch

.travis.yml, scripts/setup_venv_osx.sh
Fix in practice meant installing Python 3.5 (instead of 3.6 which came through brew).
=> [macos] packaging fix

.travis.yml, appveyor.yml, scripts/package/package-zip.sh
=> Better artifact naming

.travis.yml, Makefile
This should probably not be merged quite yet but I'm curious if this could solve https://github.com/ActivityWatch/aw-qt/issues/11.
=> Switched to trusty in Travis

.appveyor.yml, Makefile, appveyor.yml, scripts/tests/integration_tests.py
Since I rewrote the integration test script in Python it hopefully won't stall now
=> Rewrote integration script (failed attempt at getting it to run on Appveyor)

.gitmodules, Makefile
Removed submodules which no longer need to be in the top-level:
- aw-webui (now a submodule of aw-server)
- aw-client-js (now only a submodule of aw-webui)
=> Removed submodules which don't need to be directly in the bundle repo

README.md, scripts/submodule-branch.sh
Just a PR to ensure the CI passes before I merge all the stuff.
=> Preparation for upcoming 0.8 alpha

README.md
Linkified the Feature comparison table
=> Added links to other trackers

.appveyor.yml
See https://github.com/ActivityWatch/activitywatch/issues/195
=> Attempted pip-related fix

scripts/ci/install_node.ps1
=> Switched to Node v8.11.4 on Appveyor

.appveyor.yml
Downgrade and lock PyInstaller version to 3.3.1 to fix windows builds
=> Fix Windows PyInstaller builds

.appveyor.yml, .travis.yml, scripts/ci/enable_long_paths.bat
Fixes issue with long paths as described here: https://github.com/pypa/pip/issues/6279#issuecomment-526864501
=> enabled long paths on Windows (Travis and Appveyor)

.appveyor.yml, scripts/ci/install_pyhook.ps1
Fixes issues with Windows build in v0.8.1
=> v0.8.1 windows fix

aw.spec
Fixes https://github.com/ActivityWatch/activitywatch/issues/345
Fixes https://github.com/ActivityWatch/activitywatch/issues/346
=> migrated to flask-restx, updated submodules

scripts/release_notes.sh
Adds the automated release note script referenced in https://github.com/ActivityWatch/docs/pull/33
=> Add release note script to main repo

.travis.yml
Explained at  https://github.com/ActivityWatch/activitywatch/issues/370#issuecomment-597783317
=> Actually use travi's new cleanup boolean

README.md
https://github.com/ActivityWatch/activitywatch/runs/525022273?check_suite_focus=true#step:6:17
=> docs: fixed typo in README found by codespell

CONTRIBUTING.md
=> docs: added commit message guidelines to CONTRIBUTING.md

scripts/build_changelog.py
Kinda pretty now, look at the draft for v0.10.0 for an example: https://github.com/ActivityWatch/activitywatch/releases/tag/untagged-12943141739de3ab2d95
=> feat: improved generation of changelog

.github/ISSUE_TEMPLATE/config.yml
=> docs: improved issue template chooser with links to Forum, Discord, etc

scripts/package/activitywatch-setup.iss
I have no idea if this works (have not tested).
Just followed the innosetup documentation of how it's supposed to work.
Fixes https://github.com/ActivityWatch/activitywatch/issues/577
=> fix(windows): Added icon to uninstaller

scripts/logcrawler.py
The if statement that was unreachable was removed.
=> Removed Unreachable code

.github/workflows/build.yml
Hoping this will fix the SIGSEGVs.
=> ci: install Qt & xcb libs in CI environment

CONTRIBUTING.md
Fixed broken link of writing-watchers.html
=> docs: fixed broken link

.github/workflows/build.yml
Should be fine and not cause any issues, I hope.
=> ci: switched to ubuntu-latest

Makefile
Reverts ActivityWatch/activitywatch#696
=> Revert "ci: change use `python` to `python3`"

.github/workflows/build.yml, Makefile, scripts/build_changelog.py, scripts/changelog_contributors.csv
Testing the release workflow in https://github.com/ErikBjare/activitywatch/pull/1
=> Autogenerate release notes and CI releases

.github/workflows/build.yml, .gitmodules, Makefile
Ended up needing this because aw-notify is getting pretty good, but needs to be codesigned to be usable on macOS.
=> build: added extra modules and build/ci support (aw-notify and aw-watcher-input)

.tool-versions
Update the versions of poetry, nodejs, and python in the .tool-versions file.
=> chore: update tool versions
